### ISSUE TITLE
Implement support for string representation of classification targets

### ISSUE THREAD

**Issue by tuvelofstrom** [Moffran/calibrated_explanations#27]
Issue #26 highlighted the lack of support for classification support for classes represented as strings. 

Implement support for string representation of classification targets

**Comment by ww-jermaine** [comment]
Hi @tuvelofstrom!

I'm interested in contributing to your project. I was wondering if this would help with implementing support for the string representation of classification targets:

https://github.com/Moffran/calibrated_explanations/pull/55

Let me know how I can help. Thank you!

**Comment by tuvelofstrom** [comment]
Hi @ww-jermaine 

I am glad to hear you want to help!

Yes, that is probably a good idea to begin with. Our tests currently have almost 90% coverage, so you should be able to use them to ensure compatibility across the entire package.

Reach out if you have questions! 

/Tuwe

**Comment by tuvelofstrom** [comment]
I added your pull request and two tests (which are skipped by default) that test the functionality. They fail right now, but I do not have time to look into it at present. But feel free to look into it and fix whatever causes them.

I also made sure that the CI will run all tests on pull requests.

**Comment by ww-jermaine** [comment]
@tuvelofstrom Thank you so much! 

I've submitted another pull request addressing the issue. The problem was caused by the `CalibratedExplainer` not properly handling string labels in the target variable. As a fix, handling the conversion of string labels to numeric labels internally—while preserving the mapping to the original labels were added. 

Thank you for your patience! I'm still learning the subject through your examples, and I'm eager to use the library in future projects.
