### ISSUE TITLE
CatBoost and text features

### ISSUE THREAD

**Issue by GabrielZinatoSP** [Moffran/calibrated_explanations#28]
I trained a CatBoost model with categorical features and text features. When I try to apply calibrated_explanations to it, it is able to create the object, but then it bugs because of the text features. How can I proceed?

![calibrated_bug](https://github.com/Moffran/calibrated_explanations/assets/40676510/94d4d106-ec50-491e-b50b-e2e3fa54c605)

**Comment by tuvelofstrom** [comment]
Thank you for reporting the issue! I would need some additional context to be able to reproduce the error. The errors in the image are not from any code in our package, but may be caused by our package. In order to investigate further, I would need to be able to reproduce the error.

Please contact me at tuwe.lofstrom at ju.se if you cannot share information publicly.

**Comment by GabrielZinatoSP** [comment]
Thank you for your reply through email! I ended up removing the text feature from my data and retraining the model, and then it worked.

Thank you very much for your patience and I commend you on your effort of making the package better with such humility to learn and fix problems. I wish you all much success with the package, because it's a very good idea! I'm a fan already, it helped me a lot on the work I was developing 😃👍
If I come across the problem I had with the discretizer again, I'll be sure to let you guys know!

**Comment by tuvelofstrom** [comment]
Thanks! We will add a section in the README describing the current limitations of the implementation. The fact that input must be numeric is obviously something to clarify!
